name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - jupyter
  - jupyterlab
  - jupyter_dashboards
  - ipywidgets
  - notebook
  - nodejs
  - nb_conda_kernels
  - pytest
  - tornado=5.1.1
  - pip:
    - dask_labextension # https://github.com/dask/dask-labextension
    - jupyter-server-proxy
    - matlab_kernel
