version: 2.1

jobs:
  build-job:
    docker:
      - image: circleci/python:3.7


    steps:
      - checkout
      - run:
          name: Install Conda
          command: |
            ./setup/setup.py
      - run:
          name: Running Tests
          command: |
            echo 'export PATH=$HOME/miniconda/bin:$PATH' >> $BASH_ENV
            source /home/circleci/.bashrc
            pip install --user pytest
            pytest -v setup


workflows:
  version: 2
  default:
    jobs:
      - build-job
