version: 2.1

jobs:
  build-job:
    docker:
      - image: circleci/python:3.7


    steps:
      - checkout
      - run:
          name: Install Conda and Check setup
          command: |
            ./setup/configure
            ./setup/check_setup

workflows:
  version: 2
  default:
    jobs:
      - build-job
