version: 2.1

jobs:
  build-job:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: Install Conda
          command: |
            pip install --user pytest
            ./setup/setup.py
            pytest -v setup


workflows:
  version: 2
  default:
    jobs:
      - build-job
