version: 2.1

jobs:
  build-job:
    docker:
      - image: circleci/python:3.7


    steps:
      - checkout
      - run:
          name: Install Conda and Create environments
          command: |
            ./setup/configure
      - run:
          name: Running Tests
          command: |
            export PATH="$HOME/miniconda3/bin:$PATH"
            conda info
            source activate analysis-env
            ./setup/check_setup

workflows:
  version: 2
  default:
    jobs:
      - build-job
