name: tutorial
channels:
  - conda-forge
dependencies:
  - nbsphinx
  - numpydoc
  - python=3.7
  - ipython
  - recommonmark
  - sphinx_rtd_theme
  - sphinx>=1.6
  - jupyterlab
  - dask
  - xarray
  - numpy
  - watermark
  - netcdf4
  - pip:
    - sphinx_copybutton